### ISSUE TITLE
Settings are not saved on IDEA

### ISSUE THREAD

**Issue by lutin11** [andrey4623/intellij-rainbow-csv#27]
IDEA csv separator change is not saved from one session to another.

When I change csv separator from comma to semicolon it works fine during the active session, but configuration is lost when closing idea and back to comma when restarting Idea 

IntelliJ IDEA 2024.1.4 (Community Edition)
Build #IC-241.18034.62, built on June 20, 2024
Runtime version: 17.0.11+1-b1207.24 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 6.6.28-desktop-1.mga9
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 16
Registry:
  ide.balloon.shadow.size=15
  ide.experimental.ui=true
Non-Bundled Plugins:
  com.andrey4623.rainbowcsv (2.0.2)
  com.intellij.properties.bundle.editor (241.14494.150)
  Lombook Plugin (241.18034.62)
  FluentLanguage (0.4.2)
  Docker (241.18034.82)
Kotlin: 241.18034.62-IJ
Current Desktop: KDE

**Comment by AndzheyAsryan** [comment]
Same here, using Goland and have to switch to ; every time I reload the IDE.

**Comment by arnoschaefer** [comment]
Same here, still not fixed

**Comment by abehnan** [comment]
+1, also dealing with this issue

**Comment by LibertyPaul** [comment]
Fixed under #28 , but there's no movement for months unfortunately.

A temporary solution - is to download fixed code from my fork https://github.com/LibertyPaul/intellij-rainbow-csv/tree/master, build the plugin locally and to install it from file.

**Comment by camilajenny** [comment]
The bug is still present, can we somehow ask IntelliJ team to integrate it?
